import { mlClient } from '../services/mlClient.js';

const REGIONAL_SITES = [
  {
    id: 'geo_sierra_foothills',
    region: 'Sierra Foothills Corridor',
    code: 'SF-01',
    latitude: 38.5439,
    longitude: -120.9380,
    elevation_meters: 680,
    vegetation: 'Dry Pine & Chaparral',
    temperature: 36.2,
    humidity: 21.0,
    wind_speed: 18.5,
    pressure: 1004.2,
    rainfall: 0.0,
    oxygen_level: 20.9,
    ffmc: 92.4,
    dmc: 68.2,
    dc: 380.0,
    isi: 14.8,
    bui: 74.0,
    fwi: 32.5,
  },
  {
    id: 'geo_cascades_valley',
    region: 'Cascades Valley Basin',
    code: 'CV-02',
    latitude: 45.6298,
    longitude: -121.8535,
    elevation_meters: 420,
    vegetation: 'Douglas Fir & Cedar',
    temperature: 28.5,
    humidity: 42.0,
    wind_speed: 11.2,
    pressure: 1012.5,
    rainfall: 0.4,
    oxygen_level: 21.0,
    ffmc: 84.1,
    dmc: 32.0,
    dc: 210.0,
    isi: 7.2,
    bui: 42.0,
    fwi: 14.8,
  },
  {
    id: 'geo_pacific_coast_ridge',
    region: 'Pacific Coast Ridge',
    code: 'PCR-03',
    latitude: 38.2620,
    longitude: -122.1024,
    elevation_meters: 310,
    vegetation: 'Oak Woodland & Grassland',
    temperature: 29.8,
    humidity: 38.0,
    wind_speed: 22.0,
    pressure: 1014.1,
    rainfall: 0.0,
    oxygen_level: 20.95,
    ffmc: 88.6,
    dmc: 44.5,
    dc: 290.0,
    isi: 11.5,
    bui: 54.0,
    fwi: 24.2,
  },
  {
    id: 'geo_high_desert_plateau',
    region: 'High Desert Plateau',
    code: 'HDP-04',
    latitude: 34.6882,
    longitude: -117.2833,
    elevation_meters: 950,
    vegetation: 'Sagebrush & Juniper Scrub',
    temperature: 39.5,
    humidity: 14.0,
    wind_speed: 26.4,
    pressure: 998.5,
    rainfall: 0.0,
    oxygen_level: 20.8,
    ffmc: 94.8,
    dmc: 88.0,
    dc: 510.0,
    isi: 19.4,
    bui: 110.0,
    fwi: 48.0,
  },
  {
    id: 'geo_redwood_basin',
    region: 'Redwood Coastal Basin',
    code: 'RCB-05',
    latitude: 41.2033,
    longitude: -124.0046,
    elevation_meters: 150,
    vegetation: 'Coastal Redwood & Fern',
    temperature: 21.4,
    humidity: 68.0,
    wind_speed: 8.0,
    pressure: 1018.0,
    rainfall: 2.1,
    oxygen_level: 21.1,
    ffmc: 72.0,
    dmc: 18.0,
    dc: 140.0,
    isi: 3.5,
    bui: 24.0,
    fwi: 5.2,
  },
  {
    id: 'geo_angeles_forest',
    region: 'Angeles National Forest Ridge',
    code: 'ANF-06',
    latitude: 34.2500,
    longitude: -118.1500,
    elevation_meters: 1200,
    vegetation: 'Dense Chaparral & Mixed Conifer',
    temperature: 37.0,
    humidity: 18.0,
    wind_speed: 20.5,
    pressure: 1002.0,
    rainfall: 0.0,
    oxygen_level: 20.85,
    ffmc: 93.5,
    dmc: 76.0,
    dc: 440.0,
    isi: 16.2,
    bui: 88.0,
    fwi: 38.6,
  }
];

export function createGeospatialController() {
  return {
    async getGeospatialRisk(request, response) {
      try {
        const results = await Promise.all(
          REGIONAL_SITES.map(async (site) => {
            const pred = await mlClient.predictForest(site);
            return {
              id: site.id,
              region: site.region,
              code: site.code,
              latitude: site.latitude,
              longitude: site.longitude,
              elevation_meters: site.elevation_meters,
              vegetation: site.vegetation,
              telemetry: {
                temperature: site.temperature,
                humidity: site.humidity,
                wind_speed: site.wind_speed,
                pressure: site.pressure,
                rainfall: site.rainfall,
                oxygen_level: site.oxygen_level,
                fwi: site.fwi,
                isi: site.isi,
              },
              fire_probability: pred.probability,
              risk_score: pred.risk_score,
              risk_category: pred.risk_category,
              intensity: pred.risk_score / 100.0,
              forecast_risk: {
                plus_2h: Math.min(100, Number((pred.risk_score * 1.08).toFixed(1))),
                plus_4h: Math.min(100, Number((pred.risk_score * 1.15).toFixed(1))),
                plus_6h: Math.max(0, Number((pred.risk_score * 0.95).toFixed(1))),
              }
            };
          })
        );

        return response.json({
          status: 'success',
          total_locations: results.length,
          locations: results,
        });
      } catch (error) {
        return response.status(500).json({ error: error.message });
      }
    },
  };
}
