import { useEffect, useState } from "react";
import RiskBadge from "../components/RiskBadge";
import { api, getApiError } from "../services/api";

export default function History() {
  const [predictions, setPredictions] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [query, setQuery] = useState("");
  useEffect(() => { api.get("/predictions?limit=100").then(({ data }) => setPredictions(data.predictions)).catch((requestError) => setError(getApiError(requestError, "History could not be loaded"))).finally(() => setLoading(false)); }, []);
  const filtered = predictions.filter((item) => new Date(item.createdAt).toLocaleString().toLowerCase().includes(query.toLowerCase()) || String(item.prediction).includes(query));
  return <div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-ember">Archive</p><h1 className="mt-3 font-display text-5xl font-bold">Prediction history.</h1></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter date or class" className="rounded-xl border border-ink/15 bg-white px-4 py-3 text-sm outline-none focus:ring-4 focus:ring-ember/20" /></div>{error && <p className="mt-8 rounded-xl bg-ember/10 px-4 py-3 text-sm text-ember">{error}</p>}<section className="mt-10 overflow-x-auto rounded-[1.5rem] bg-white shadow-sm">{loading ? <p className="p-8 text-ink/50">Loading history...</p> : <table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-ink/10 text-xs uppercase tracking-wider text-ink/45"><tr><th className="px-6 py-4">Date</th><th className="px-6 py-4">Model class</th><th className="px-6 py-4">Class 1 probability</th><th className="px-6 py-4">Inputs</th></tr></thead><tbody>{filtered.map((item) => <tr key={item._id} className="border-b border-ink/5 last:border-0"><td className="px-6 py-5 text-ink/60">{new Date(item.createdAt).toLocaleString()}</td><td className="px-6 py-5"><RiskBadge prediction={item.prediction} /></td><td className="px-6 py-5 font-bold">{Math.round(item.probability * 100)}%</td><td className="px-6 py-5 text-ink/55">{item.inputs.temperature}°C · {item.inputs.humidity}% humidity · {item.inputs.windSpeed} km/h wind</td></tr>)}</tbody></table>}{!loading && !filtered.length && <p className="p-8 text-ink/50">No matching predictions.</p>}</section></div>;
}
