/**
 * FireGuard AI - Canonical Building & Zone Graph Topologies
 * Includes 2D spatial coordinates for floorplan rendering, zone types,
 * flammability ratings, base occupancies, and bidirectional connection graphs.
 */

export const INITIAL_BUILDINGS = [
  {
    id: "building_a",
    name: "Building A — Advanced Research Facility",
    code: "BLDG-A",
    campus: "North Science Sector",
    total_area_sqm: 3200,
    coordinates: { lat: 37.7749, lng: -122.4194 },
    zones: [
      {
        id: "bldg_a_elec",
        name: "Electrical Room",
        type: "electrical",
        flammability: 4.8,
        occupancy: 2,
        max_occupancy: 4,
        is_exit: false,
        coordinates: { x: 50, y: 50, width: 140, height: 110 },
        connected_zones: [
          { target_id: "bldg_a_corridor", distance_meters: 6.0, hazard_factor: 1.3 },
          { target_id: "bldg_a_storage", distance_meters: 8.5, hazard_factor: 1.1 },
        ],
      },
      {
        id: "bldg_a_lab1",
        name: "Lab 1 (Chemical)",
        type: "lab",
        flammability: 4.2,
        occupancy: 12,
        max_occupancy: 25,
        is_exit: false,
        coordinates: { x: 210, y: 50, width: 180, height: 110 },
        connected_zones: [
          { target_id: "bldg_a_corridor", distance_meters: 5.0, hazard_factor: 1.2 },
          { target_id: "bldg_a_lab2", distance_meters: 10.0, hazard_factor: 1.4 },
        ],
      },
      {
        id: "bldg_a_lab2",
        name: "Lab 2 (Optics & Laser)",
        type: "lab",
        flammability: 3.5,
        occupancy: 8,
        max_occupancy: 20,
        is_exit: false,
        coordinates: { x: 410, y: 50, width: 180, height: 110 },
        connected_zones: [
          { target_id: "bldg_a_lab1", distance_meters: 10.0, hazard_factor: 1.4 },
          { target_id: "bldg_a_corridor", distance_meters: 5.0, hazard_factor: 1.0 },
          { target_id: "bldg_a_exit_b", distance_meters: 7.0, hazard_factor: 0.8 },
        ],
      },
      {
        id: "bldg_a_corridor",
        name: "Central Corridor",
        type: "corridor",
        flammability: 1.8,
        occupancy: 5,
        max_occupancy: 50,
        is_exit: false,
        coordinates: { x: 50, y: 180, width: 540, height: 80 },
        connected_zones: [
          { target_id: "bldg_a_elec", distance_meters: 6.0, hazard_factor: 1.3 },
          { target_id: "bldg_a_lab1", distance_meters: 5.0, hazard_factor: 1.2 },
          { target_id: "bldg_a_lab2", distance_meters: 5.0, hazard_factor: 1.0 },
          { target_id: "bldg_a_storage", distance_meters: 4.0, hazard_factor: 1.1 },
          { target_id: "bldg_a_exit_a", distance_meters: 8.0, hazard_factor: 0.7 },
          { target_id: "bldg_a_exit_b", distance_meters: 8.0, hazard_factor: 0.7 },
        ],
      },
      {
        id: "bldg_a_storage",
        name: "Chemical Storage",
        type: "storage",
        flammability: 4.9,
        occupancy: 1,
        max_occupancy: 5,
        is_exit: false,
        coordinates: { x: 50, y: 280, width: 180, height: 120 },
        connected_zones: [
          { target_id: "bldg_a_corridor", distance_meters: 4.0, hazard_factor: 1.2 },
          { target_id: "bldg_a_elec", distance_meters: 8.5, hazard_factor: 1.1 },
          { target_id: "bldg_a_exit_a", distance_meters: 6.0, hazard_factor: 0.9 },
        ],
      },
      {
        id: "bldg_a_exit_a",
        name: "Exit A (West Stairwell)",
        type: "exit",
        flammability: 1.0,
        occupancy: 0,
        max_occupancy: 100,
        is_exit: true,
        coordinates: { x: 250, y: 280, width: 160, height: 120 },
        connected_zones: [
          { target_id: "bldg_a_corridor", distance_meters: 8.0, hazard_factor: 0.7 },
          { target_id: "bldg_a_storage", distance_meters: 6.0, hazard_factor: 0.9 },
        ],
      },
      {
        id: "bldg_a_exit_b",
        name: "Exit B (East Main Entrance)",
        type: "exit",
        flammability: 1.0,
        occupancy: 0,
        max_occupancy: 150,
        is_exit: true,
        coordinates: { x: 430, y: 280, width: 160, height: 120 },
        connected_zones: [
          { target_id: "bldg_a_corridor", distance_meters: 8.0, hazard_factor: 0.7 },
          { target_id: "bldg_a_lab2", distance_meters: 7.0, hazard_factor: 0.8 },
        ],
      },
    ],
  },
  {
    id: "building_b",
    name: "Building B — Academic & Compute Complex",
    code: "BLDG-B",
    campus: "East Academic Sector",
    total_area_sqm: 4500,
    coordinates: { lat: 37.7790, lng: -122.4120 },
    zones: [
      {
        id: "bldg_b_server",
        name: "High-Density Server Room",
        type: "server_room",
        flammability: 4.6,
        occupancy: 3,
        max_occupancy: 6,
        is_exit: false,
        coordinates: { x: 50, y: 50, width: 160, height: 110 },
        connected_zones: [
          { target_id: "bldg_b_corridor", distance_meters: 5.0, hazard_factor: 1.3 },
          { target_id: "bldg_b_class1", distance_meters: 12.0, hazard_factor: 1.1 },
        ],
      },
      {
        id: "bldg_b_class1",
        name: "Classroom 1 (Auditorium)",
        type: "classroom",
        flammability: 2.2,
        occupancy: 65,
        max_occupancy: 90,
        is_exit: false,
        coordinates: { x: 230, y: 50, width: 170, height: 110 },
        connected_zones: [
          { target_id: "bldg_b_corridor", distance_meters: 4.0, hazard_factor: 1.0 },
          { target_id: "bldg_b_class2", distance_meters: 8.0, hazard_factor: 1.0 },
        ],
      },
      {
        id: "bldg_b_class2",
        name: "Classroom 2 (Lecture Hall)",
        type: "classroom",
        flammability: 2.2,
        occupancy: 45,
        max_occupancy: 70,
        is_exit: false,
        coordinates: { x: 420, y: 50, width: 170, height: 110 },
        connected_zones: [
          { target_id: "bldg_b_class1", distance_meters: 8.0, hazard_factor: 1.0 },
          { target_id: "bldg_b_corridor", distance_meters: 4.0, hazard_factor: 1.0 },
          { target_id: "bldg_b_exit_b", distance_meters: 6.0, hazard_factor: 0.7 },
        ],
      },
      {
        id: "bldg_b_corridor",
        name: "Main Promenade Corridor",
        type: "corridor",
        flammability: 1.5,
        occupancy: 15,
        max_occupancy: 80,
        is_exit: false,
        coordinates: { x: 50, y: 180, width: 540, height: 80 },
        connected_zones: [
          { target_id: "bldg_b_server", distance_meters: 5.0, hazard_factor: 1.3 },
          { target_id: "bldg_b_class1", distance_meters: 4.0, hazard_factor: 1.0 },
          { target_id: "bldg_b_class2", distance_meters: 4.0, hazard_factor: 1.0 },
          { target_id: "bldg_b_storage", distance_meters: 5.0, hazard_factor: 1.1 },
          { target_id: "bldg_b_exit_a", distance_meters: 7.0, hazard_factor: 0.7 },
          { target_id: "bldg_b_exit_b", distance_meters: 7.0, hazard_factor: 0.7 },
        ],
      },
      {
        id: "bldg_b_storage",
        name: "Facilities & Archive Storage",
        type: "storage",
        flammability: 4.1,
        occupancy: 1,
        max_occupancy: 5,
        is_exit: false,
        coordinates: { x: 50, y: 280, width: 160, height: 120 },
        connected_zones: [
          { target_id: "bldg_b_corridor", distance_meters: 5.0, hazard_factor: 1.1 },
          { target_id: "bldg_b_exit_a", distance_meters: 6.0, hazard_factor: 0.8 },
        ],
      },
      {
        id: "bldg_b_exit_a",
        name: "Exit A (South Atrium)",
        type: "exit",
        flammability: 1.0,
        occupancy: 0,
        max_occupancy: 200,
        is_exit: true,
        coordinates: { x: 230, y: 280, width: 170, height: 120 },
        connected_zones: [
          { target_id: "bldg_b_corridor", distance_meters: 7.0, hazard_factor: 0.7 },
          { target_id: "bldg_b_storage", distance_meters: 6.0, hazard_factor: 0.8 },
        ],
      },
      {
        id: "bldg_b_exit_b",
        name: "Exit B (North Concourse)",
        type: "exit",
        flammability: 1.0,
        occupancy: 0,
        max_occupancy: 200,
        is_exit: true,
        coordinates: { x: 420, y: 280, width: 170, height: 120 },
        connected_zones: [
          { target_id: "bldg_b_corridor", distance_meters: 7.0, hazard_factor: 0.7 },
          { target_id: "bldg_b_class2", distance_meters: 6.0, hazard_factor: 0.7 },
        ],
      },
    ],
  },
  {
    id: "building_c",
    name: "Building C — Operations & Logistics Center",
    code: "BLDG-C",
    campus: "South Logistics Sector",
    total_area_sqm: 2800,
    coordinates: { lat: 37.7680, lng: -122.4250 },
    zones: [
      {
        id: "bldg_c_kitchen",
        name: "Commercial Kitchen",
        type: "kitchen",
        flammability: 4.7,
        occupancy: 8,
        max_occupancy: 15,
        is_exit: false,
        coordinates: { x: 50, y: 50, width: 170, height: 110 },
        connected_zones: [
          { target_id: "bldg_c_corridor", distance_meters: 4.5, hazard_factor: 1.4 },
          { target_id: "bldg_c_storage", distance_meters: 7.0, hazard_factor: 1.2 },
        ],
      },
      {
        id: "bldg_c_office",
        name: "Administrative Offices",
        type: "office",
        flammability: 2.5,
        occupancy: 28,
        max_occupancy: 45,
        is_exit: false,
        coordinates: { x: 240, y: 50, width: 350, height: 110 },
        connected_zones: [
          { target_id: "bldg_c_corridor", distance_meters: 4.0, hazard_factor: 1.0 },
          { target_id: "bldg_c_exit_b", distance_meters: 9.0, hazard_factor: 0.8 },
        ],
      },
      {
        id: "bldg_c_corridor",
        name: "Central Service Hall",
        type: "corridor",
        flammability: 1.9,
        occupancy: 4,
        max_occupancy: 40,
        is_exit: false,
        coordinates: { x: 50, y: 180, width: 540, height: 80 },
        connected_zones: [
          { target_id: "bldg_c_kitchen", distance_meters: 4.5, hazard_factor: 1.4 },
          { target_id: "bldg_c_office", distance_meters: 4.0, hazard_factor: 1.0 },
          { target_id: "bldg_c_storage", distance_meters: 4.0, hazard_factor: 1.1 },
          { target_id: "bldg_c_exit_a", distance_meters: 6.5, hazard_factor: 0.7 },
          { target_id: "bldg_c_exit_b", distance_meters: 6.5, hazard_factor: 0.7 },
        ],
      },
      {
        id: "bldg_c_storage",
        name: "Dry Goods & Supply Storage",
        type: "storage",
        flammability: 4.3,
        occupancy: 2,
        max_occupancy: 6,
        is_exit: false,
        coordinates: { x: 50, y: 280, width: 170, height: 120 },
        connected_zones: [
          { target_id: "bldg_c_corridor", distance_meters: 4.0, hazard_factor: 1.1 },
          { target_id: "bldg_c_kitchen", distance_meters: 7.0, hazard_factor: 1.2 },
          { target_id: "bldg_c_exit_a", distance_meters: 5.5, hazard_factor: 0.8 },
        ],
      },
      {
        id: "bldg_c_exit_a",
        name: "Exit A (Loading Bay Exit)",
        type: "exit",
        flammability: 1.0,
        occupancy: 0,
        max_occupancy: 120,
        is_exit: true,
        coordinates: { x: 240, y: 280, width: 160, height: 120 },
        connected_zones: [
          { target_id: "bldg_c_corridor", distance_meters: 6.5, hazard_factor: 0.7 },
          { target_id: "bldg_c_storage", distance_meters: 5.5, hazard_factor: 0.8 },
        ],
      },
      {
        id: "bldg_c_exit_b",
        name: "Exit B (Staff Entrance)",
        type: "exit",
        flammability: 1.0,
        occupancy: 0,
        max_occupancy: 120,
        is_exit: true,
        coordinates: { x: 420, y: 280, width: 170, height: 120 },
        connected_zones: [
          { target_id: "bldg_c_corridor", distance_meters: 6.5, hazard_factor: 0.7 },
          { target_id: "bldg_c_office", distance_meters: 9.0, hazard_factor: 0.8 },
        ],
      },
    ],
  },
];
